variables:
  DOCKER_REGISTRY:
    description: "URL of the Docker registry to use."
    # The v2 registry seems to have authentication issues when used here.
    value: "https://index.docker.io/v1/"
  DOCKER_USER:
    description: "Username of the registry user."
  DOCKER_PASS:
    description: "Password of the registry user."
  DOCKER_IMAGE:
    description: "Image to push to."

# Define the stages.
stages:
  # Create a static code analysis stage.
  - analyze
  # Create an app package building stage. There is no separate deploy stage, because docker buildx
  # doesn't have any built in support for building a multi-arch image manifest, and deploying it
  # later. Relevant GitHub issues:
  # - https://github.com/docker/buildx/issues/166
  # - https://github.com/docker/buildx/issues/430
  - build

editorconfig-checker:
  # Add to the analysis stage.
  stage: analyze
  # Use the latest ec Docker image.
  image: mstruebing/editorconfig-checker:latest
  # Check that all text complies with the EditorConfig file.
  script: ec

shfmt:
  stage: analyze
  # Use the latest Alpine Linux shfmt Docker image.
  image: mvdan/shfmt:latest-alpine
  rules:
    - changes:
        # Watch for changes in the source.
        - "src/*"
  # Check that all shell code has proper formatting.
  script: shfmt -d src

shellcheck:
  stage: analyze
  # Use the latest stable ShellCheck Docker image.
  image: koalaman/shellcheck-alpine:stable
  rules:
    - changes:
        - "src/*"
  # Check that all shell code is proper.
  script: shellcheck --external-sources src/*

build:
  # Add to the build stage.
  stage: build
  # Run in our Docker in Docker (dind) + buildx plugin image.
  image: yamdi/dind-buildx
  services:
    # Run dockerd in the background.
    - name: yamdi/dind-buildx:dockerd
      # Specify an alias so that the service will be available under "docker".
      alias: docker
  script:
    # Disallow usage of undefined variables. The options "-e" for exiting if a command exits with a
    # non-zero status is already set.
    - set -u
    # Just to be safe, initialize the variable we'll be using to store arguments.
    - args="";
    # If we are running on the default branch.
    - if [ "${CI_COMMIT_BRANCH:-}" = "$CI_DEFAULT_BRANCH" ]; then
    # Log into the Docker registry.
    - |
      printf %s "$DOCKER_PASS" | docker login "$DOCKER_REGISTRY" \
      --username "$DOCKER_USER" --password-stdin
    # Append the push argument.
    - args="$args --push"
    - fi
    # If we are building for any architectures other than our own.
    - if [ "$CI_RUNNER_EXECUTABLE_ARCH" != "$DOCKER_TARGET_ARCH" ]; then
    # Configure binfmt_misc to use QEMU. This is necessary to fix this issue:
    # https://github.com/docker/buildx/issues/584
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    # Create a new builder instance whose driver will support multi-arch building.
    - docker buildx create --use
    - fi
    # We schedule daily builds so that security fixes can be integrated into the builds, in which
    # case we don't want to cache anything. If this is a job triggered by a commit, though, we can
    # cache all we want and get fast builds. Here, we selectively choose the sources for which we
    # will cache. For the rest, "--no-cache" isn't even necessary because this is running on dry CI.
    - |
      if [ "$CI_PIPELINE_SOURCE" = "push" ] ||
        [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ] ||
        [ "$CI_PIPELINE_SOURCE" = "external_pull_request_event" ] ||
        [ "$CI_PIPELINE_SOURCE" = "webide" ]; then
    # Cache from the first tag belonging to this job. this is arbitrary - unless the CI
    # configuration has changed, any of the tags would work.
    - args="$args --cache-from $DOCKER_IMAGE:$(printf %s "$DOCKER_TAGS" | cut -d' ' -f1)"
    - fi
    # Retrieve the date from the predefined CI datetime variable.
    - date=$(printf %s "$CI_PIPELINE_CREATED_AT" | cut -dT -f1 | tr -d -)
    # Iterate over the tags specified. The default IFS delimiter includes spaces.
    - for tag in $DOCKER_TAGS; do
    # # Construct the tag arguments.
    - args="$args --tag $DOCKER_IMAGE:$tag --tag $DOCKER_IMAGE:$tag-$date"; done
    # Build and push the images. Even if we aren't using the cache to build, we want to make sure
    # to be writing inline cache metadata to the image.
    - |
      docker buildx build --build-arg DOCKER_BASE_IMAGE="$DOCKER_BASE_IMAGE" \
      --build-arg BUILDKIT_INLINE_CACHE=1 --platform="$DOCKER_TARGET_ARCH" $args .
  parallel:
    matrix:
      - DOCKER_BASE_IMAGE: eclipse-temurin:17
        DOCKER_TARGET_ARCH: linux/amd64,linux/arm64,linux/arm
        DOCKER_TAGS: latest latest-ubuntu
