#!/bin/sh

# shellcheck source=src/yamdi-utils
. yamdi-utils

if [ "$(whoami)" != nonroot ]; then
  su -c "echo \"$*\" >\"$COMMAND_INPUT_FILE\"" -s /bin/sh nonroot
else
  echo "$@" >"$COMMAND_INPUT_FILE"
fi
